name: C Doxygen CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Build
      run: |
        cd source
        make

    - name: Generate documentation
      run: |
        cd source
        make docs

    - name: Archive documentation
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: source/docs/html/
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false